CREATE TABLE pouch_category (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    buff_key TEXT NOT NULL,
    CONSTRAINT uq_pouch_category_name UNIQUE (name)
);

CREATE TABLE pouch_item (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    category_id INTEGER NOT NULL,
    CONSTRAINT uq_pouch_item_name UNIQUE (name),
    CONSTRAINT fk_pouch_item_category
        FOREIGN KEY (category_id) REFERENCES pouch_category(id)
);

CREATE TABLE favorite_category (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    owner_type TEXT NOT NULL,
    owner_name TEXT NOT NULL,
    persona TEXT NOT NULL DEFAULT '',
    category_id INTEGER NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT ck_fav_cat_owner_type CHECK (owner_type IN ('driver', 'blade')),
    CONSTRAINT fk_fav_cat_category
        FOREIGN KEY (category_id) REFERENCES pouch_category(id)
);

CREATE TABLE favorite_item (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    owner_type TEXT NOT NULL,
    owner_name TEXT NOT NULL,
    persona TEXT NOT NULL DEFAULT '',
    item_id INTEGER NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT ck_fav_item_owner_type CHECK (owner_type IN ('driver', 'blade')),
    CONSTRAINT fk_fav_item_item
        FOREIGN KEY (item_id) REFERENCES pouch_item(id)
);

INSERT INTO pouch_category (name, buff_key)
VALUES
    ('staple_foods', 'dmg_barrier'),
    ('veggies', 'hp_restore'),
    ('meats', 'phys_def'),
    ('seafood', 'ether_def'),
    ('desserts', 'arts_recharge'),
    ('drinks', 'party_gauge'),
    ('instruments', 'special_recharge'),
    ('art', 'affinity_gain'),
    ('literature', 'special_damage'),
    ('board_games', 'blade_art'),
    ('cosmetics', 'start_affinity'),
    ('textiles', 'affinity_loss'),
    ('charms', 'party_gauge');

INSERT INTO pouch_item (name, category_id)
SELECT x.name, c.id
FROM (
    VALUES
        ('pan_fried_tartari', 'meats'),
        ('coral_reversi', 'board_games'),
        ('cream_orange_paratha', 'staple_foods'),
        ('ardainian_bear_carving', 'art'),
        ('quoteletta', 'meats'),
        ('steamwork_organ', 'instruments'),
        ('addams_embercakes', 'veggies'),
        ('snow_crystal_vase', 'art'),
        ('juicy_samod', 'staple_foods'),
        ('silken_stool', 'textiles'),
        ('jenerossi_tea', 'drinks'),
        ('woodgrain_alphorn', 'instruments'),
        ('cloud_sea_crab_sticks', 'seafood'),
        ('final_chorus', 'art'),
        ('wood_dye_waistcloth', 'textiles'),
        ('abyssturgeon_medallion', 'seafood'),
        ('dried_sunfish', 'seafood'),
        ('cedarwood_koto', 'instruments'),
        ('fizz_juice', 'drinks'),
        ('roly_poly_maracas', 'instruments'),
        ('sky_jewel_tart', 'desserts'),
        ('genbu_weave_cloth', 'textiles'),
        ('melodious_melon_parfait', 'desserts'),
        ('flurrycomb', 'cosmetics'),
        ('fried_octomayo', 'staple_foods'),
        ('moonstar_lipstick', 'cosmetics'),
        ('thawing_mille_feuille', 'desserts'),
        ('titan_oil_hand_cream', 'cosmetics'),
        ('fondant_rice_cake', 'staple_foods'),
        ('montecoran_doll', 'art'),
        ('snowbaby_potato_salad', 'veggies'),
        ('sneak_thief_king', 'board_games'),
        ('massive_mushroom_pie', 'staple_foods'),
        ('frozen_odifa', 'drinks'),
        ('sunshine_pie', 'meats'),
        ('spicy_stralu', 'meats'),
        ('poached_fruit_samod', 'staple_foods'),
        ('tantal_icecube', 'art'),
        ('leaf_weave_cape', 'textiles'),
        ('snow_dumplings', 'desserts'),
        ('fruity_rice_ball', 'desserts'),
        ('torigoth_snowpouch', 'textiles'),
        ('steamflake_tabbouleh', 'veggies'),
        ('red_opal_lipstick', 'cosmetics'),
        ('lunana_smoothie', 'drinks'),
        ('jeweled_billiard_balls', 'board_games'),
        ('gladiator_wrestling', 'board_games'),
        ('masters_curry', 'staple_foods'),
        ('indoline_tea', 'drinks'),
        ('copper_ephem_statue', 'art'),
        ('fish_and_herb_broth', 'seafood'),
        ('les_awfuls', 'literature'),
        ('aromalocaris_saute', 'seafood'),
        ('black_flower_field', 'art'),
        ('neon_grape_flan', 'desserts'),
        ('imperial_secret_escapes', 'literature'),
        ('army_issue_violin', 'instruments'),
        ('salvaging_made_easy', 'literature'),
        ('char_grilled_grumbird', 'meats'),
        ('portrait_of_ger', 'art'),
        ('torigoth_marinade', 'veggies'),
        ('leftherian_life', 'board_games'),
        ('blossom_custard', 'desserts'),
        ('conch_hairpin', 'cosmetics'),
        ('tricolor_bowl', 'staple_foods'),
        ('dont_feed_the_armu', 'board_games'),
        ('torigonda', 'instruments'),
        ('black_roast_coffee', 'drinks'),
        ('fonsan_viola', 'instruments'),
        ('sno_bake_cheesecake', 'desserts'),
        ('curled_eyelashes', 'cosmetics'),
        ('prickly_snowpickle', 'veggies'),
        ('crinkly_wool', 'textiles'),
        ('marine_stir_fry', 'seafood'),
        ('smack_a_nopon', 'board_games'),
        ('honey_au_lait', 'drinks'),
        ('hammerplate_snare', 'instruments'),
        ('stuffed_meaty_carrot', 'veggies'),
        ('sparkly_snow_perfume', 'cosmetics'),
        ('estral_steak', 'meats'),
        ('adventures_of_myram', 'literature'),
        ('felmeri_fairy_statue', 'art'),
        ('astrology_made_simple', 'literature'),
        ('tasty_sausage', 'meats'),
        ('nopopo_yard', 'board_games'),
        ('army_field_manual', 'board_games'),
        ('zaproast_power_bowl', 'meats'),
        ('vinaigrette_ice_cabbage', 'veggies'),
        ('scarlet_shamisen', 'instruments'),
        ('steamed_veg_stralu', 'veggies'),
        ('sparkling_snowglobe', 'art'),
        ('whitebait_samod_hotpot', 'seafood'),
        ('elastifying_tonic', 'cosmetics'),
        ('addams_supercakes', 'veggies'),
        ('ardainian_arms_album', 'literature'),
        ('codweave_safety_blanky', 'textiles'),
        ('pipestraw_smoothie', 'drinks'),
        ('twinklejuice', 'drinks'),
        ('nopon_chess_set', 'board_games')
) AS x(name, category)
JOIN pouch_category c ON c.name = x.category;

INSERT INTO favorite_category (owner_type, owner_name, persona, category_id, sort_order)
SELECT x.owner_type, x.owner_name, x.persona, c.id, x.sort_order
FROM (
    VALUES
        ('driver', 'rex', '', 'drinks', 0),
        ('driver', 'rex', '', 'art', 1),
        ('driver', 'nia', '', 'seafood', 0),
        ('driver', 'nia', '', 'textiles', 1),
        ('driver', 'merefu', '', 'veggies', 0),
        ('driver', 'merefu', '', 'art', 1),
        ('driver', 'zig', '', 'meats', 0),
        ('driver', 'zig', '', 'textiles', 1),
        ('driver', 'tora', '', 'drinks', 0),
        ('driver', 'tora', '', 'instruments', 1),
        ('blade', 'seihai', 'pyra', 'veggies', 0),
        ('blade', 'seihai', 'pyra', 'literature', 1),
        ('blade', 'seihai', 'mythra', 'desserts', 0),
        ('blade', 'seihai', 'mythra', 'art', 1),
        ('blade', 'suzaku', '', 'seafood', 0),
        ('blade', 'suzaku', '', 'board_games', 1),
        ('blade', 'pyauko', '', 'meats', 0),
        ('blade', 'pyauko', '', 'board_games', 1),
        ('blade', 'hana js', '', 'staple_foods', 0),
        ('blade', 'hana js', '', 'instruments', 1),
        ('blade', 'hana jk', '', 'veggies', 0),
        ('blade', 'hana jk', '', 'art', 1),
        ('blade', 'hana jd', '', 'staple_foods', 0),
        ('blade', 'hana jd', '', 'textiles', 1),
        ('blade', 'saika', '', 'meats', 0),
        ('blade', 'saika', '', 'literature', 1),
        ('blade', 'kaguduchi', '', 'desserts', 0),
        ('blade', 'kaguduchi', '', 'cosmetics', 1),
        ('blade', 'wadatumi', '', 'desserts', 0),
        ('blade', 'wadatumi', '', 'art', 1),
        ('blade', 'nia', '', 'seafood', 0),
        ('blade', 'nia', '', 'instruments', 1),
        ('blade', 'boreas', '', 'staple_foods', 0),
        ('blade', 'boreas', '', 'cosmetics', 1),
        ('blade', 'crossette', '', 'staple_foods', 0),
        ('blade', 'crossette', '', 'desserts', 1),
        ('blade', 'dahlla', '', 'veggies', 0),
        ('blade', 'dahlla', '', 'cosmetics', 1),
        ('blade', 'floren', '', 'veggies', 0),
        ('blade', 'floren', '', 'art', 1),
        ('blade', 'vess', '', 'seafood', 0),
        ('blade', 'vess', '', 'cosmetics', 1),
        ('blade', 'azami', '', 'drinks', 0),
        ('blade', 'azami', '', 'literature', 1),
        ('blade', 'herald', '', 'drinks', 0),
        ('blade', 'herald', '', 'board_games', 1),
        ('blade', 'kosmos', '', 'staple_foods', 0),
        ('blade', 'kosmos', '', 'board_games', 1),
        ('blade', 'sheba', '', 'desserts', 0),
        ('blade', 'sheba', '', 'textiles', 1),
        ('blade', 'agate', '', 'drinks', 0),
        ('blade', 'agate', '', 'art', 1),
        ('blade', 'dagas', '', 'seafood', 0),
        ('blade', 'dagas', '', 'art', 1),
        ('blade', 'gorg', '', 'desserts', 0),
        ('blade', 'gorg', '', 'textiles', 1),
        ('blade', 'telos', '', 'instruments', 0),
        ('blade', 'telos', '', 'literature', 1),
        ('blade', 'zanobia', '', 'meats', 0),
        ('blade', 'zanobia', '', 'literature', 1),
        ('blade', 'adenine', '', 'veggies', 0),
        ('blade', 'adenine', '', 'literature', 1),
        ('blade', 'kora', '', 'drinks', 0),
        ('blade', 'kora', '', 'cosmetics', 1),
        ('blade', 'nim', '', 'seafood', 0),
        ('blade', 'nim', '', 'instruments', 1),
        ('blade', 'ursula', '', 'desserts', 0),
        ('blade', 'ursula', '', 'cosmetics', 1),
        ('blade', 'perun', '', 'seafood', 0),
        ('blade', 'perun', '', 'textiles', 1),
        ('blade', 'praxis', '', 'desserts', 0),
        ('blade', 'praxis', '', 'literature', 1),
        ('blade', 'vale', '', 'desserts', 0),
        ('blade', 'vale', '', 'textiles', 1),
        ('blade', 'wulfric', '', 'staple_foods', 0),
        ('blade', 'wulfric', '', 'literature', 1),
        ('blade', 'electra', '', 'meats', 0),
        ('blade', 'electra', '', 'instruments', 1),
        ('blade', 'finch', '', 'veggies', 0),
        ('blade', 'finch', '', 'cosmetics', 1),
        ('blade', 'godfrey', '', 'meats', 0),
        ('blade', 'godfrey', '', 'instruments', 1),
        ('blade', 'kasandra', '', 'staple_foods', 0),
        ('blade', 'kasandra', '', 'cosmetics', 1),
        ('blade', 'poppibuster', '', 'meats', 0),
        ('blade', 'poppibuster', '', 'board_games', 1),
        ('blade', 'newt', '', 'meats', 0),
        ('blade', 'newt', '', 'instruments', 1),
        ('blade', 'perceval', '', 'drinks', 0),
        ('blade', 'perceval', '', 'art', 1),
        ('blade', 'theory', '', 'veggies', 0),
        ('blade', 'theory', '', 'board_games', 1),
        ('blade', 'momo', '', 'desserts', 0),
        ('blade', 'momo', '', 'charms', 1),
        ('blade', 'fiora', '', 'seafood', 0),
        ('blade', 'fiora', '', 'cosmetics', 1),
        ('blade', 'shulk', '', 'veggies', 0),
        ('blade', 'shulk', '', 'literature', 1),
        ('blade', 'elma', '', 'seafood', 0),
        ('blade', 'elma', '', 'art', 1),
        ('blade', 'kamuya', '', 'drinks', 0),
        ('blade', 'kamuya', '', 'board_games', 1)
) AS x(owner_type, owner_name, persona, category, sort_order)
JOIN pouch_category c ON c.name = x.category;

INSERT INTO favorite_item (owner_type, owner_name, persona, item_id, sort_order)
SELECT x.owner_type, x.owner_name, x.persona, i.id, x.sort_order
FROM (
    VALUES
        ('driver', 'rex', '', 'pan_fried_tartari', 0),
        ('driver', 'rex', '', 'coral_reversi', 1),
        ('driver', 'nia', '', 'cream_orange_paratha', 0),
        ('driver', 'nia', '', 'ardainian_bear_carving', 1),
        ('driver', 'merefu', '', 'quoteletta', 0),
        ('driver', 'merefu', '', 'steamwork_organ', 1),
        ('driver', 'zig', '', 'addams_embercakes', 0),
        ('driver', 'zig', '', 'snow_crystal_vase', 1),
        ('driver', 'tora', '', 'juicy_samod', 0),
        ('driver', 'tora', '', 'silken_stool', 1),
        ('blade', 'seihai', 'pyra', 'jenerossi_tea', 0),
        ('blade', 'seihai', 'pyra', 'woodgrain_alphorn', 1),
        ('blade', 'seihai', 'mythra', 'cloud_sea_crab_sticks', 0),
        ('blade', 'seihai', 'mythra', 'final_chorus', 1),
        ('blade', 'suzaku', '', 'wood_dye_waistcloth', 0),
        ('blade', 'suzaku', '', 'abyssturgeon_medallion', 1),
        ('blade', 'pyauko', '', 'dried_sunfish', 0),
        ('blade', 'pyauko', '', 'cedarwood_koto', 1),
        ('blade', 'hana js', '', 'fizz_juice', 0),
        ('blade', 'hana js', '', 'roly_poly_maracas', 1),
        ('blade', 'hana jk', '', 'sky_jewel_tart', 0),
        ('blade', 'hana jk', '', 'genbu_weave_cloth', 1),
        ('blade', 'hana jd', '', 'melodious_melon_parfait', 0),
        ('blade', 'hana jd', '', 'flurrycomb', 1),
        ('blade', 'saika', '', 'fried_octomayo', 0),
        ('blade', 'saika', '', 'moonstar_lipstick', 1),
        ('blade', 'kaguduchi', '', 'thawing_mille_feuille', 0),
        ('blade', 'kaguduchi', '', 'titan_oil_hand_cream', 1),
        ('blade', 'wadatumi', '', 'fondant_rice_cake', 0),
        ('blade', 'wadatumi', '', 'montecoran_doll', 1),
        ('blade', 'nia', '', 'snowbaby_potato_salad', 0),
        ('blade', 'nia', '', 'sneak_thief_king', 1),
        ('blade', 'boreas', '', 'massive_mushroom_pie', 0),
        ('blade', 'boreas', '', 'frozen_odifa', 1),
        ('blade', 'crossette', '', 'sunshine_pie', 0),
        ('blade', 'crossette', '', 'spicy_stralu', 1),
        ('blade', 'dahlla', '', 'poached_fruit_samod', 0),
        ('blade', 'dahlla', '', 'tantal_icecube', 1),
        ('blade', 'floren', '', 'leaf_weave_cape', 0),
        ('blade', 'floren', '', 'snow_dumplings', 1),
        ('blade', 'vess', '', 'fruity_rice_ball', 0),
        ('blade', 'vess', '', 'torigoth_snowpouch', 1),
        ('blade', 'azami', '', 'steamflake_tabbouleh', 0),
        ('blade', 'azami', '', 'red_opal_lipstick', 1),
        ('blade', 'herald', '', 'lunana_smoothie', 0),
        ('blade', 'herald', '', 'jeweled_billiard_balls', 1),
        ('blade', 'kosmos', '', 'gladiator_wrestling', 0),
        ('blade', 'kosmos', '', 'masters_curry', 1),
        ('blade', 'sheba', '', 'indoline_tea', 0),
        ('blade', 'sheba', '', 'copper_ephem_statue', 1),
        ('blade', 'agate', '', 'fish_and_herb_broth', 0),
        ('blade', 'agate', '', 'les_awfuls', 1),
        ('blade', 'dagas', '', 'aromalocaris_saute', 0),
        ('blade', 'dagas', '', 'black_flower_field', 1),
        ('blade', 'gorg', '', 'neon_grape_flan', 0),
        ('blade', 'gorg', '', 'imperial_secret_escapes', 1),
        ('blade', 'telos', '', 'army_issue_violin', 0),
        ('blade', 'telos', '', 'salvaging_made_easy', 1),
        ('blade', 'zanobia', '', 'char_grilled_grumbird', 0),
        ('blade', 'zanobia', '', 'portrait_of_ger', 1),
        ('blade', 'adenine', '', 'torigoth_marinade', 0),
        ('blade', 'adenine', '', 'leftherian_life', 1),
        ('blade', 'kora', '', 'blossom_custard', 0),
        ('blade', 'kora', '', 'conch_hairpin', 1),
        ('blade', 'nim', '', 'tricolor_bowl', 0),
        ('blade', 'nim', '', 'dont_feed_the_armu', 1),
        ('blade', 'ursula', '', 'torigonda', 0),
        ('blade', 'ursula', '', 'steamwork_organ', 1),
        ('blade', 'perun', '', 'black_roast_coffee', 0),
        ('blade', 'perun', '', 'fonsan_viola', 1),
        ('blade', 'praxis', '', 'sno_bake_cheesecake', 0),
        ('blade', 'praxis', '', 'curled_eyelashes', 1),
        ('blade', 'vale', '', 'prickly_snowpickle', 0),
        ('blade', 'vale', '', 'crinkly_wool', 1),
        ('blade', 'wulfric', '', 'marine_stir_fry', 0),
        ('blade', 'wulfric', '', 'smack_a_nopon', 1),
        ('blade', 'electra', '', 'honey_au_lait', 0),
        ('blade', 'electra', '', 'hammerplate_snare', 1),
        ('blade', 'finch', '', 'stuffed_meaty_carrot', 0),
        ('blade', 'finch', '', 'sparkly_snow_perfume', 1),
        ('blade', 'godfrey', '', 'estral_steak', 0),
        ('blade', 'godfrey', '', 'adventures_of_myram', 1),
        ('blade', 'kasandra', '', 'felmeri_fairy_statue', 0),
        ('blade', 'kasandra', '', 'astrology_made_simple', 1),
        ('blade', 'poppibuster', '', 'tasty_sausage', 0),
        ('blade', 'poppibuster', '', 'nopopo_yard', 1),
        ('blade', 'newt', '', 'army_field_manual', 0),
        ('blade', 'newt', '', 'zaproast_power_bowl', 1),
        ('blade', 'perceval', '', 'vinaigrette_ice_cabbage', 0),
        ('blade', 'perceval', '', 'scarlet_shamisen', 1),
        ('blade', 'theory', '', 'steamed_veg_stralu', 0),
        ('blade', 'theory', '', 'sparkly_snow_perfume', 1),
        ('blade', 'momo', '', 'masters_curry', 0),
        ('blade', 'momo', '', 'sparkling_snowglobe', 1),
        ('blade', 'fiora', '', 'whitebait_samod_hotpot', 0),
        ('blade', 'fiora', '', 'elastifying_tonic', 1),
        ('blade', 'shulk', '', 'addams_supercakes', 0),
        ('blade', 'shulk', '', 'ardainian_arms_album', 1),
        ('blade', 'elma', '', 'codweave_safety_blanky', 0),
        ('blade', 'elma', '', 'pipestraw_smoothie', 1),
        ('blade', 'kamuya', '', 'twinklejuice', 0),
        ('blade', 'kamuya', '', 'nopon_chess_set', 1)
) AS x(owner_type, owner_name, persona, item, sort_order)
JOIN pouch_item i ON i.name = x.item;
