const ROLE = {
  ATK: 'Attacker',
  TNK: 'Tank',
  HLR: 'Healer'
} as const

const WEAPON = {
  SEIHAI: 'seihai',
  SUZAKU: 'suzaku',
  SAIKA: 'saika',
  BALL: 'ball',
  KATANA: 'katana',
  CANNON: 'cannon',
  HANA_SHIELD: 'hana shield',
  HANA_ARMS: 'hana arms',
  HANA_SABER: 'hana saber',
  AXE: 'axe',
  HAMMER: 'hammer',
  WHIP: 'whip',
  LANCE: 'lance',
  UCHIGATANA: 'uchigatana',
  TWIN_RINGS: 'twin rings',
  CLAWS: 'claws',
  NIA: 'nia',
  SHULK: 'shulk',
  ELMA: 'elma',
} as const

const ELEMENT = {
  FIRE: 'fire',
  WATER: 'water',
  WIND: 'wind',
  ICE: 'ice',
  ELEC: 'electricity',
  EARTH: 'earth',
  DARK: 'dark',
  LIGHT: 'light',
} as const

const EFFECT = {
  BREAK: 'break',
  TOPPLE: 'topple',
  LAUNCH: 'launch',
  SMASH: 'smash',
} as const

const BLADE = {
  SEIHAI: 'seihai',
  SUZAKU: 'suzaku',
  PYAUKO: 'pyauko',
  HANA_JD: 'hana jd',
  HANA_JK: 'hana hk',
  HANA_JS: 'hana js',
  SAIKA: 'saika',
  KAGUDUCHI: 'kaguduchi',
  WADATUMI: 'wadatumi',
  NIA: 'nia',
  BOREAS: 'boreas',
  CROSSETTE: 'crossette',
  DAHLLA: 'dahlla',
  FLOREN: 'floren',
  VESS: 'vess',
  AZUMI: 'azami',
  HERALD: 'herald',
  KOSMOS: 'kosmos',
  SHEBA: 'sheba',
  AGATE: 'agate',
  DAGAS: 'dagas',
  GORG: 'gorg',
  TELOS: 'telos',
  ZANOBIA: 'zanobia',
  ADENINE: 'adenine',
  KORA: 'kora',
  NIM: 'nim',
  URSULA: 'ursula',
  PERUN: 'perun',
  PRAXIS: 'praxis',
  VALE: 'vale',
  WULFRIC: 'wulfric',
  ELECTRA: 'electra',
  FINCH: 'finch',
  GODFREY: 'godfrey',
  KASANDRA: 'kasandra',
  POPPIBUSTER: 'poppibuster',
  NEWT: 'newt',
  PERCEVAL: 'perceval',
  THEORY: 'theory',
  MOMO: 'momo',
  FIORA: 'fiora',
  SHULK: 'shulk',
  ELMA: 'elma',
  KAMUYA: 'kamuya',
} as const

const DRIVER = {
  REX: 'rex',
  NIA: 'nia',
  MEREFU: 'merefu',
  ZIG: 'zig',
  TORA: 'tora',
} as const

export default {
  ROLE,
  WEAPON,
  ELEMENT,
  EFFECT,
  BLADE,
  DRIVER,
}